-- ============================================================
-- MIGRATION: Add dosing_timing table
-- Run this in Supabase SQL Editor after schema.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS dosing_timing (
  id                SERIAL PRIMARY KEY,
  peptide_id        TEXT NOT NULL REFERENCES peptides(id),
  optimal_timing    TEXT NOT NULL,
  loading_phase     TEXT,
  maintenance_phase TEXT,
  off_cycle         TEXT,
  timing_notes      TEXT NOT NULL
);

ALTER TABLE dosing_timing ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read dosing_timing" ON dosing_timing FOR SELECT USING (true);

INSERT INTO dosing_timing (peptide_id, optimal_timing, loading_phase, maintenance_phase, off_cycle, timing_notes) VALUES

('ghrp2',
'Bedtime (10-11pm) is the primary dose — aligns with the body''s natural GH pulse during slow-wave sleep. If dosing 2x daily: add a pre-workout or mid-afternoon fasted dose. If 3x daily: morning fasted, pre-workout fasted, and bedtime.',
'No loading phase required.',
'2-3 injections daily throughout the 8-12 week cycle.',
'4 weeks completely off after every 8-12 week cycle to prevent GHS-R1a receptor desensitization.',
'Administer minimum 2 hours post-meal. Wait 30 minutes after injection before eating. Avoid high-intensity cardio immediately before injection — elevated cortisol blunts the GH pulse. Avoid alcohol within 4 hours of injection.'),

('ipamorelin',
'Bedtime is the most impactful single dose (aligns with natural GH pulse). If 2x daily: add pre-workout or mid-afternoon fasted. If 3x daily: morning fasted, pre-workout fasted, and bedtime. Co-inject with Mod GRF 1-29 in the same syringe for maximum effect.',
'No loading phase required.',
'1-3 injections daily. Many users use continuously given the clean hormonal profile.',
'Optional 4-week break after 12-16 weeks. Not strictly required given minimal side effect profile.',
'Empty stomach is essential — minimum 90 minutes post-meal. Wait 30-45 minutes post-injection before eating. Draw Ipamorelin and Mod GRF 1-29 into one insulin syringe for convenient co-injection.'),

('mk677',
'Evening or bedtime preferred — leverages the sleep GH pulse. If vivid dreams or sleep disruption occur, shift to morning. Consistent daily timing is more important than the specific hour.',
'First 2 weeks: expect more pronounced hunger and water retention as the body adapts. This subsides.',
'Single daily dose. Some use continuously year-round with periodic blood glucose monitoring.',
'Optional 8-week break once per year. Many use continuously without issues.',
'Can be taken with or without food — oral bioavailability is not significantly affected by meals. Monitor fasting blood glucose every 4-6 weeks. Maintain consistent daily timing for stable IGF-1 levels.'),

('hexarelin',
'Morning fasted (primary dose). Evening fasted (second dose if using 2x daily). Some practitioners rotate: 1 week Hexarelin, 1 week Ipamorelin, to partially preserve receptor sensitivity.',
'No loading phase. Effects are immediate but decline rapidly with desensitization.',
'Maximum 2 injections daily. Desensitization begins within the first week.',
'Mandatory 4-6 week break after every 4-6 week cycle. Some take 1 week off every 3 weeks on-cycle to partially maintain receptor sensitivity.',
'Administer in a fully fasted state. Due to significant prolactin elevation, consider cabergoline 0.25-0.5 mg twice weekly as support. Cortisol elevation is significant — monitor mood and recovery.'),

('sermorelin',
'Bedtime only (9-11pm, empty stomach). This is non-negotiable — Sermorelin works by stimulating the pituitary during the natural circadian GH release window that occurs 1-2 hours after sleep onset. Morning administration is largely wasted.',
'No loading phase. Effects build gradually over 4-6 weeks as pituitary function normalizes.',
'Single nightly injection. Results take 4-6 weeks to become noticeable.',
'Generally not cycled. Used long-term (3-6+ months). Some take 1 month off every 6 months.',
'Always fasted (2+ hours post-meal). Do not use in the morning or afternoon. Always pair with a GHRP (Ipamorelin preferred) for synergistic effect. Refrigerate after reconstitution.'),

('modgrf',
'Always co-administered with a GHRP — inject simultaneously in the same syringe. Optimal windows mirror the GHRP being used: bedtime, pre-workout fasted, or mid-afternoon fasted.',
'No loading phase.',
'2-3x daily, always paired with a GHRP. Cycle with whatever GHRP it is paired with.',
'Cycle with the GHRP it is paired with.',
'Fasted state is mandatory for meaningful GH pulse. Draw Mod GRF 1-29 and Ipamorelin into one insulin syringe — inject together. The combination is far more effective than either alone. Do not use without a GHRP.'),

('tesamorelin',
'Morning is standard but any consistent daily time works given the longer half-life. Some prefer bedtime to leverage sleep GH patterns.',
'No loading phase required.',
'Once daily injection. Most visceral fat reduction visible at 3-6 months.',
'Used long-term per FDA protocol. Some practitioners cycle 6 months on, 1 month off.',
'No strict fasting requirement unlike shorter-acting GHRH analogs. Monitor fasting blood glucose periodically. Consistent daily timing is more important than the specific time of day.'),

('cjc1295dac',
'Once weekly — choose a consistent day (e.g., every Monday morning). Due to the 6-8 day half-life, precise time-of-day is less critical. Some add Ipamorelin injections at day 3-4 post-CJC injection for an additional pulsatile GH spike.',
'No loading phase.',
'Once weekly throughout the 8-12 week cycle.',
'4 weeks off after every 8-12 week cycle.',
'Unlike shorter-acting GHRHs, strict fasting is less critical due to tonic rather than pulsatile GH release. The weekly dosing schedule creates a GH bleed rather than discrete pulses — some practitioners prefer this; others prefer the more physiological pulsatile approach of Mod GRF 1-29.'),

('bpc157',
'For systemic and injury healing: morning fasted (flexible — timing is not critical for subcutaneous dosing). For gut and GI issues: oral route 20-30 minutes before meals. For local injury: inject near the site at any time.',
'No loading phase. Effects on healing begin within days.',
'1-2 injections daily throughout the protocol duration.',
'4-12 weeks depending on injury severity. Discontinue once healed or significantly improved.',
'For musculoskeletal injuries, injecting as close to the injury site as possible (not necessarily into the joint — periarticular subcutaneous is sufficient) concentrates the peptide locally. Oral administration in water is specifically effective for GI conditions. No food timing restrictions for subcutaneous dosing.'),

('tb500',
'Loading phase timing is flexible — any time of day. Due to systemic distribution, timing relative to food or exercise does not significantly affect efficacy unlike GH peptides.',
'2-2.5 mg twice weekly for 4-6 weeks (e.g., Monday and Thursday).',
'2-2.5 mg once weekly.',
'Continue maintenance as needed. Full discontinuation when injury is resolved.',
'Unlike most peptides, TB-500 does not require fasting. A single subcutaneous injection anywhere on the body distributes systemically to all injured tissues. Stack with BPC-157 during the loading phase for comprehensive healing coverage. Inject subcutaneously — IM is not necessary.'),

('ghkcu',
'Topical: AM after cleansing before moisturizer; PM as part of evening routine. Injectable: morning, no food timing requirement.',
'Topical: no loading. Injectable: start 3x weekly.',
'Topical: AM and PM ongoing. Injectable: 3-5x weekly for 8-12 weeks.',
'Topical: continuous indefinite use. Injectable: 8-12 weeks on, 4 weeks off.',
'Topical: apply to clean, slightly damp skin for better absorption. Allow 60 seconds to absorb before applying next skincare product. Avoid immediately after strong acids or retinoids — wait 20 minutes. Injectable: no fasting requirement. Refrigerate reconstituted peptide.'),

('kpv',
'Oral (gut protocol): 20-30 minutes before meals for maximum mucosal contact time. Topical (skin): AM and PM application. Injectable: morning, flexible timing.',
'No loading phase required.',
'1-2x daily throughout the 8-12 week protocol.',
'8-12 weeks on, 4 weeks off.',
'For gut inflammation: oral route in capsules or dissolved in water taken before meals ensures maximum contact with inflamed mucosal tissue. For skin conditions: apply topical formulation to affected area. For systemic anti-inflammatory effects: subcutaneous injection is preferred over oral. Combine with BPC-157 oral protocol for comprehensive gut healing.'),

('ara290',
'Morning injection. Consistent daily timing is important for the nerve repair protocol — do not skip days during the 28-day course.',
'28 consecutive daily injections (the standard clinical protocol). Do not interrupt mid-course.',
'Evaluate response after 28 days. Repeat 28-day courses as needed based on symptom improvement.',
'Standard protocol is 28 days on, then evaluate. Repeat courses can be run after assessment.',
'Complete the full 28-day course without interruption for meaningful nerve fiber regeneration. Clinical improvement in small fiber density is measurable at 6 months via corneal confocal microscopy or skin biopsy. Monitor neuropathy symptoms (pain, numbness, burning) throughout the course.'),

('aod9604',
'Morning fasted is essential — inject 30-45 minutes before breakfast. Exercise within 1-2 hours of injection maximizes fat burning through catecholamine synergy with beta-3 adrenergic receptor activation. A second dose pre-workout (if 2 hours fasted) can be added.',
'No loading phase required.',
'Single morning fasted dose. Can add pre-workout dose if fasted 2+ hours.',
'4 weeks off after every 12-16 week cycle.',
'Fasted state is critical for lipolytic effect — insulin completely blocks beta-3 adrenergic receptor activity. Do not eat within 30 minutes post-injection. Morning fasted exercise amplifies fat burning significantly. Avoid beta-blocker medications as they directly antagonize the mechanism.'),

('frag176',
'Morning fasted (primary dose — most important). Pre-workout fasted (second dose if using 2x daily). The pre-workout dose is particularly effective as exercise amplifies the lipolytic effect of beta-3 adrenergic receptor stimulation.',
'No loading phase.',
'1-2 fasted injections daily.',
'4 weeks off after every 8-12 week cycle.',
'Like AOD-9604, fasted state is critical. Avoid within 2 hours of carbohydrate-rich meals — insulin directly opposes the lipolytic mechanism. The morning fasted + pre-workout fasted split maximizes the two key windows for beta-3 adrenergic fat burning during the day.'),

('semaglutide',
'Same day each week — choose a day and stick to it (e.g., every Monday morning). Time of day is flexible. Most choose morning for routine consistency. Inject into abdomen, thigh, or upper arm — rotate sites.',
'Start at 0.25 mg weekly for 4 weeks (tolerance building, not therapeutic dose).',
'Titrate every 4 weeks: 0.25mg → 0.5mg → 1.0mg → 1.7mg → 2.4mg (Wegovy). Slower titration if GI side effects are significant.',
'Designed for long-term continuous use. Discontinuation results in weight regain within weeks-months.',
'Rotate injection sites weekly to prevent lipodystrophy. Nausea management: eat smaller portions, avoid fatty and spicy foods, consider ondansetron in early weeks. Titrate slowly — there is no benefit to rushing to higher doses. Resistance training and 1g/lb protein intake are non-negotiable companions.'),

('tirzepatide',
'Same day each week. Morning preferred. Inject in abdomen, thigh, or upper arm — rotate sites weekly.',
'Start at 2.5 mg weekly for 4 weeks.',
'Titrate every 4 weeks: 2.5mg → 5mg → 7.5mg → 10mg → 12.5mg → 15mg. Slower titration if GI side effects occur.',
'Designed for long-term continuous use. Like semaglutide, discontinuation results in weight regain.',
'Rotate injection sites. GI side effects typically peak at 2-4 weeks after each dose increase, then subside. Eat slowly, stop when full, avoid high-fat meals especially on injection day and the day after. Resistance training and high protein intake are essential to preserve muscle mass throughout treatment.'),

('semax',
'Morning (primary — only dose for 1x daily use). If dosing 2x: add late morning or early afternoon only. Never administer in the evening — stimulating effects will disrupt sleep.',
'No loading phase. Some users start at lower end of dosing range (200-300 mcg) and titrate up.',
'1-2x daily intranasal during the 2-4 week on-period.',
'1-2 weeks completely off after every 2-4 week on-period. Cycling is essential to prevent tolerance and maintain BDNF response.',
'Administer intranasally — 2-3 drops per nostril, tilt head back slightly. Effects felt within 30-60 minutes. Staggering with Selank (take Selank first, then Semax 10-15 minutes later) smooths the stimulating edge. Never use after 2pm. N-Acetyl Semax Amidate is approximately 3x more potent — halve the dose.'),

('selank',
'Morning or mid-morning. Can be used situationally before stressful events or on a consistent daily schedule. More flexible timing than Semax due to its anxiolytic rather than stimulating profile.',
'No loading phase.',
'1-2x daily intranasal during the 10-14 day on-period.',
'After 10-14 days on, use as needed rather than on a strict schedule. Not strictly required to cycle.',
'Intranasal: 2-3 drops per nostril. Effects felt within 20-40 minutes. Optimal Semax/Selank protocol: take Selank first to establish the anxiolytic baseline, then Semax 10-15 minutes later for cognitive stimulation without the anxiogenic edge. Store in refrigerator — degrades faster at room temperature than other peptides.'),

('dihexa',
'Morning on an empty stomach for maximum CNS absorption. Transdermal: apply to thin-skinned areas (inner wrist, inner forearm, or neck) for best absorption.',
'Start at the lower end (10 mg) regardless of target dose. Assess response before increasing.',
'2-3x per week maximum — Monday, Wednesday, Friday schedule is common.',
'4-6 weeks on, 4 weeks completely off. Effects persist for weeks after stopping due to long half-life and sustained synaptogenesis.',
'Extremely potent — do not exceed 3x per week under any circumstances. Effects accumulate and may not be obvious in week 1. Transdermal with DMSO carrier significantly increases absorption — apply to clean, dry skin. Do not combine with Semax at full doses of both simultaneously.'),

('nadplus',
'IV: Morning clinic visit (2-3 hour session). Start infusion rate at 1 mL/min and increase gradually as tolerated to minimize flushing and chest tightness. Oral NMN/NR: morning with or without food, consistent daily timing.',
'IV loading: 5-10 consecutive daily infusions (loading course). Oral: begin at 500 mg daily.',
'IV maintenance: 1-3x weekly. Oral: 500-1000 mg daily ongoing.',
'IV: loading courses 1-2x per year; maintenance ongoing. Oral: continuous indefinite use.',
'Do not drink alcohol on the same day as IV NAD+ — alcohol immediately consumes NAD+ via alcohol dehydrogenase, wasting the therapy. Take TMG (trimethylglycine) same morning to support methylation. Pair with resveratrol daily for SIRT1 activation synergy. Slow the IV drip if flushing or chest tightness occurs.'),

('cerebrolysin',
'Morning IM or IV clinic visit, daily for the full course duration. Same time each day — consistency matters for neurotrophic factor accumulation.',
'Daily injections for the complete 10-20 day course without interruption. Do not skip days.',
'Repeat full courses 2-4x per year with 6-8 week gaps between courses.',
'6-8 weeks between courses minimum.',
'Do not interrupt a course midway — the neurotrophic cascade builds throughout the protocol. Cognitive effects are often noticed mid-course (days 5-10). IM injection is a viable home administration option. Refrigerate; use within 24 hours of opening ampoule. Hyperbaric oxygen therapy (HBOT) is a strong synergistic companion for neurological protocols.'),

('epitalon',
'Bedtime preferred — specifically supports circadian melatonin normalization and aligns with pineal gland activity. Some protocols split the dose: half AM, half PM.',
'10-20 consecutive daily injections completing the full course without interruption.',
'Repeat courses 1-2x per year. Spring (March-April) and fall (September-October) timing is the traditional protocol.',
'3-6 months between courses.',
'Complete the full course without skipping days — telomerase activation requires sustained exposure. Run concurrent with Thymalin for the classic Russian longevity combination. Bedtime administration specifically supports circadian rhythm normalization. Store lyophilized peptide in freezer; reconstituted peptide refrigerated and used within 2 weeks.'),

('thymalin',
'Morning injection. 10 consecutive days without a single missed day.',
'10 mg daily for 10 consecutive days — this is both the loading and maintenance protocol.',
'Repeat 1-2x per year. Traditional Russian protocol uses spring and fall timing.',
'3-6 months between courses.',
'Spring (March-April) and fall (September-October) timing aligns with seasonal immune demands. Do not skip days during the 10-day course. Run concurrently with Epitalon for the classic Khavinson longevity protocol. No food timing requirement. Store refrigerated.'),

('motsc',
'Pre-workout (30-60 minutes before exercise) is optimal — exercise significantly amplifies MOTS-c AMPK activation, creating powerful synergy for metabolic improvements and performance.',
'No loading phase.',
'3-5 injections per week. Mon/Wed/Fri/Sat or Mon/Tue/Thu/Fri/Sat scheduling.',
'4 weeks off after every 8-12 week cycle.',
'Pre-workout timing creates the greatest metabolic benefit through AMPK synergy with exercise. Monitor blood glucose especially during and after exercise as insulin sensitivity is significantly enhanced — hypoglycemia is a real risk if you exercise intensely after injection without adequate carbohydrate intake. Stack with Humanin on the same injection days for the comprehensive MDP protocol.'),

('humanin',
'Morning injection, 3x per week (Monday/Wednesday/Friday). Consistent schedule preferred over daily to allow JAK2/STAT3 signaling recovery between doses.',
'No loading phase.',
'3 injections per week throughout the 8-12 week cycle.',
'4 weeks off after every 8-12 week cycle.',
'The S14G modification (HNG) is 1000x more potent than native Humanin — use HNG analog. Monday/Wednesday/Friday scheduling creates consistent 2-day recovery windows between doses. Stack with MOTS-c on the same injection days for the comprehensive mitochondria-derived peptide (MDP) longevity protocol. No food timing requirement.'),

('ss31',
'Morning injection, daily or 5 days on / 2 days off schedule. Consistent daily administration maintains cardiolipin protection and mitochondrial membrane stability.',
'No loading phase.',
'Daily subcutaneous injection throughout the 4-12 week course.',
'Evaluate response at 4-12 weeks. Repeat courses as needed.',
'No food timing restrictions. Store refrigerated and administer immediately after reconstitution. Consistent daily administration is more important than specific time of day. Do not use warming or shaking to dissolve — gentle swirl only to preserve peptide integrity.'),

('pt141',
'45-60 minutes before intended sexual activity. Evening administration is typical. Peak effect occurs at 60-90 minutes post-injection, with duration of 6-12 hours. Start at the lowest effective dose (0.5-1 mg) to assess nausea response.',
'Start at 0.5 mg to assess tolerance. Titrate to 1-2 mg based on response and tolerability.',
'As needed. Maximum once every 3 days.',
'As-needed only. No defined cycling protocol.',
'Pre-medicate with ondansetron (Zofran) 4 mg taken 30 minutes before PT-141 injection — this significantly reduces nausea. Nausea is worst at 60-90 minutes and resolves by 3-4 hours. Blood pressure may transiently increase 20-30 mmHg. Most effective when not used more frequently than twice per week. Can be combined with PDE5 inhibitors for additive effect.'),

('melanotan2',
'Evening injection to sleep through the worst nausea period (peak nausea 1-3 hours post-injection). Always start at 0.25 mg regardless of intended final dose.',
'0.25 mg daily in evenings for 1-2 weeks, increasing gradually to 0.5-1 mg as tolerance to nausea builds.',
'0.5-1 mg every 2-3 days to maintain pigmentation.',
'No defined off-cycle. Use maintenance doses as needed to maintain desired pigmentation.',
'Evening administration is critical — sleeping through the nausea window at 1-3 hours post-injection makes the compound far more tolerable. Use sunscreen even without sun exposure to control tanning extent, as MT-II sensitizes melanocytes even to ambient light. Pre-medicate with ondansetron if nausea is severe. Perform a full skin check with a dermatologist before starting — document existing moles.'),

('kisspeptin',
'Pulsatile pump protocol: subcutaneous injection every 90 minutes (mimics natural kisspeptin signaling). Simplified protocol without a pump: morning and evening injections for approximately 2 pulses per day.',
'Not applicable — protocol depends on research or clinical context.',
'Pump-based pulsatile dosing or 1-2x daily subcutaneous injections.',
'Not yet standardized. Follow physician or research protocol guidance.',
'Pulsatile administration is significantly more effective than continuous infusion due to KISS1R receptor desensitization with continuous stimulation. The 90-minute pulse interval mimics the natural GnRH/kisspeptin oscillation. If a subcutaneous pump is not available, 1-2x daily injections are a practical alternative though less physiologically optimal.'),

('ta1',
'Monday and Thursday subcutaneous injection (creates consistent 3-4 day spacing). Morning or evening — no food timing requirement. Consistent biweekly spacing is the key parameter.',
'No loading phase for standard immune support protocols.',
'1.6 mg twice weekly on non-consecutive days.',
'4-8 weeks for acute immune support; up to 6 months for clinical indications.',
'Monday/Thursday scheduling creates the most consistent spacing. No fasting required. Refrigerate; stable at room temperature for short periods during travel. Concurrent high-dose Vitamin D3 (5000-10000 IU daily) significantly enhances T-cell and immune function synergistically.'),

('ll37',
'Topical: AM after cleansing before moisturizer; PM as part of evening routine. Injectable: morning, no strict food timing requirement.',
'No loading phase for topical. Injectable: start at lower dose to assess inflammatory response.',
'Topical: AM and PM daily. Injectable: 3-5x weekly.',
'Acute topical use: 2-4 weeks for wound healing; ongoing for antimicrobial skin barrier support. Injectable: 2-4 weeks.',
'For wound healing apply topical directly to clean wound bed. Injectable is preferred for systemic antimicrobial or immune effects. Vitamin D3 supplementation (5000+ IU daily) is the primary inducer of endogenous LL-37 production — combining exogenous LL-37 with D3 addresses both supply and production simultaneously.'),

('collagen',
'Any time — morning with breakfast is most common. Post-workout timing (within 60 minutes after training) with Vitamin C is optimal for directing amino acids to connective tissue repair. Consistency is more important than precise timing.',
'No loading phase. Benefits accumulate gradually over 8-12 weeks.',
'10-20 g daily continuously. Safe for indefinite daily use.',
'No cycling required. Designed for continuous long-term use.',
'Must be taken with Vitamin C (500-1000 mg) at the same time — it is the enzymatic cofactor for collagen hydroxylation. Without it, collagen synthesis is significantly impaired regardless of how much collagen peptide is consumed. Post-workout timing leverages the anabolic window for connective tissue. Consistent daily use compounds over months — do not expect results in the first 2 weeks.'),

('matrixyl',
'AM after cleansing as part of morning skincare routine. Can also be applied PM. Twice daily use maximizes results.',
'No loading phase. Begin with once daily if skin sensitivity is a concern.',
'AM and/or PM daily application — continuous ongoing use.',
'Continuous use. Effects are maintained only with ongoing application and continue to improve over months.',
'Apply to clean, slightly damp skin — the moisture aids penetration. Layer: cleanser → toner → Matrixyl serum → moisturizer → SPF (AM). Allow 60 seconds to absorb before applying the next product. Results are measurable at 4-8 weeks but continue to improve with sustained use over 3-6 months. Do not apply immediately after strong AHAs — wait 15-20 minutes.'),

('snap8',
'AM and PM application as part of skincare routine. Most effective when used consistently twice daily to target expression lines.',
'No loading phase — begin with full application protocol immediately.',
'1-2x daily ongoing application.',
'Continuous use required. Expression lines return to baseline within weeks of stopping as the SNARE competition effect dissipates.',
'Apply specifically to expression line areas: forehead, crow''s feet, glabellar lines (11s). Allow full absorption before layering other products. Effects build gradually over 4-8 weeks. Combine with Matrixyl in the same routine — Matrixyl addresses static (collagen-related) wrinkles while Snap-8 addresses dynamic (movement-related) expression lines. Together they provide comprehensive wrinkle reduction.');

